version: '3.8'
services:
  db:
    image: postgres:15
    container_name: gerenciador_veiculos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gerenciador_veiculos
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

  db_test:
    image: postgres:15
    container_name: gerenciador_veiculos_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gerenciador_veiculos_test
    ports:
      - '5434:5432'
    volumes:
      - db_test_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d/init_test.sql

volumes:
  db_data:
  db_test_data: